const toolDetailTemplate = (name: string, summary: string, highlights: string[]) => `# ${name}

${summary}

## 适合谁看

- 想快速判断这个条目是否值得收藏的人
- 想了解主要能力、适用场景和上手方式的人
- 希望在同类产品里快速做选择的人

## 主要亮点

${highlights.map((item) => `- ${item}`).join("\n")}

## 使用建议

1. 先访问官网或产品页，确认它当前的功能边界和定价策略。
2. 再结合你的工作流判断它更适合做原型验证、协作开发，还是内容生产。
3. 如果准备长期使用，建议顺手确认导出能力、协作方式和稳定性。
`

export const fallbackCategories = [
  { id: "vibe-prototyping", name: "灵感原型", icon: "💡", channelType: "vibe-tools" },
  { id: "vibe-pages", name: "页面生成", icon: "🪄", channelType: "vibe-tools" },
  { id: "vibe-fullstack", name: "全栈构建", icon: "🧱", channelType: "vibe-tools" },
  { id: "vibe-ide", name: "AI 编程环境", icon: "⌘", channelType: "vibe-tools" },
  { id: "vibe-agent-coding", name: "Agent 编程", icon: "🤖", channelType: "vibe-tools" },
  { id: "vibe-backend", name: "数据后端", icon: "🗄️", channelType: "vibe-tools" },
  { id: "vibe-automation", name: "自动化流程", icon: "🔄", channelType: "vibe-tools" },
  { id: "vibe-deploy", name: "部署发布", icon: "🚀", channelType: "vibe-tools" },
  { id: "product-efficiency-collaboration", name: "效率协作", icon: "🧩", channelType: "vibe-products" },
  { id: "product-content-creation", name: "内容创作", icon: "✍️", channelType: "vibe-products" },
  { id: "product-multimedia", name: "多媒体", icon: "🎬", channelType: "vibe-products" },
  { id: "product-learning-education", name: "学习教育", icon: "📚", channelType: "vibe-products" },
  { id: "product-marketing-growth", name: "营销增长", icon: "📣", channelType: "vibe-products" },
  { id: "product-business-finance", name: "商业金融", icon: "💼", channelType: "vibe-products" },
  { id: "product-health-lifestyle", name: "健康生活", icon: "🌿", channelType: "vibe-products" },
] as const

export const fallbackTools = [
  {
    id: "tool-cursor",
    name: "Cursor",
    slug: "cursor",
    description: "最常被提到的 AI 编程工具之一，适合以代码为中心的 Vibe Coding 工作流。",
    logo: "/placeholder-logo.svg",
    categoryId: "vibe-ide",
    channelType: "vibe-tools",
    websiteUrl: "https://cursor.com",
    previewImageUrl: "/placeholder.jpg",
    fullDescription: toolDetailTemplate("Cursor", "一款围绕 AI 编程协作体验打造的 IDE 产品。", [
      "适合重度代码编辑、重构和连续开发",
      "在 Vibe Coding 语境里讨论度很高",
      "从需求到实现的协作链路比较顺滑",
    ]),
    publishedAt: "2026-04-19T02:00:00.000Z",
    weeklyViews: 213,
    status: "published",
  },
  {
    id: "tool-lovable",
    name: "Lovable",
    slug: "lovable",
    description: "用自然语言快速搭产品原型和 Web 应用，适合非传统开发者快速试错。",
    logo: "/placeholder-logo.png",
    categoryId: "vibe-fullstack",
    channelType: "vibe-tools",
    websiteUrl: "https://lovable.dev",
    previewImageUrl: "/placeholder.jpg",
    fullDescription: toolDetailTemplate("Lovable", "一款强调自然语言生成应用原型与页面的构建工具。", [
      "适合快速验证产品想法",
      "更偏向原型和轻量 Web 应用生成",
      "很适合非工程背景用户参与产品搭建",
    ]),
    publishedAt: "2026-04-17T05:00:00.000Z",
    weeklyViews: 164,
    status: "published",
  },
  {
    id: "tool-bolt",
    name: "Bolt",
    slug: "bolt",
    description: "强调在线生成、运行和修改应用，适合快速迭代 MVP。",
    logo: "/placeholder.svg",
    categoryId: "vibe-pages",
    channelType: "vibe-tools",
    websiteUrl: "https://bolt.new",
    previewImageUrl: "/placeholder.jpg",
    fullDescription: toolDetailTemplate("Bolt", "一款强调即时生成、即时运行、即时修改的在线构建工具。", [
      "适合快速生成 MVP 和页面实验",
      "像一个可以立刻运行的产品沙盒",
      "适合做短链路设计验证",
    ]),
    publishedAt: "2026-04-13T08:30:00.000Z",
    weeklyViews: 137,
    status: "published",
  },
  {
    id: "tool-supabase",
    name: "Supabase",
    slug: "supabase",
    description: "适合做登录、数据库、对象存储和实时能力的后端底座。",
    logo: "/placeholder-logo.svg",
    categoryId: "vibe-backend",
    channelType: "vibe-tools",
    websiteUrl: "https://supabase.com",
    previewImageUrl: "/placeholder.jpg",
    fullDescription: toolDetailTemplate("Supabase", "一套适合中小团队快速起步的后端基础设施组合。", [
      "数据库、鉴权、存储和 Edge Functions 能力集中",
      "适合和生成式前端一起搭配",
      "很适合快速上线 MVP",
    ]),
    publishedAt: "2026-04-11T08:00:00.000Z",
    weeklyViews: 102,
    status: "published",
  },
  {
    id: "tool-n8n",
    name: "n8n",
    slug: "n8n",
    description: "把 AI、Webhook 和第三方服务串起来的自动化工作流工具。",
    logo: "/placeholder-logo.svg",
    categoryId: "vibe-automation",
    channelType: "vibe-tools",
    websiteUrl: "https://n8n.io",
    previewImageUrl: "/placeholder.jpg",
    fullDescription: toolDetailTemplate("n8n", "一款适合把 AI 流程、表单和通知系统串联起来的自动化平台。", [
      "适合快速验证 Agent 工作流",
      "连接外部服务的能力很强",
      "对非纯工程团队也比较友好",
    ]),
    publishedAt: "2026-04-08T07:20:00.000Z",
    weeklyViews: 88,
    status: "published",
  },
  {
    id: "tool-vercel",
    name: "Vercel",
    slug: "vercel",
    description: "适合前端产品的部署发布与预览协作，和生成式开发流程搭配顺滑。",
    logo: "/placeholder-logo.svg",
    categoryId: "vibe-deploy",
    channelType: "vibe-tools",
    websiteUrl: "https://vercel.com",
    previewImageUrl: "/placeholder.jpg",
    fullDescription: toolDetailTemplate("Vercel", "一款适合快速部署前端产品和 AI Web 应用的发布平台。", [
      "预览环境和上线链路很顺",
      "适合快节奏试错和产品迭代",
      "和现代 React 技术栈兼容度高",
    ]),
    publishedAt: "2026-04-06T06:30:00.000Z",
    weeklyViews: 59,
    status: "published",
  },
  {
    id: "product-linear",
    name: "Linear",
    slug: "linear",
    description: "产品团队协作产品里的成熟样本，信息密度、首页节奏和结构组织都很稳。",
    logo: "/placeholder-logo.svg",
    categoryId: "product-efficiency-collaboration",
    channelType: "vibe-products",
    websiteUrl: "https://linear.app/",
    previewImageUrl: "/placeholder.jpg",
    fullDescription: toolDetailTemplate("Linear", "一个适合从效率协作视角拆页面与结构的产品案例。", [
      "首页设计克制，卖点表达非常干净",
      "信息架构清晰，适合参考复杂工具如何保持秩序",
      "团队协作产品的专业感和节奏感都很成熟",
    ]),
    referenceBadges: ["首页设计", "信息架构"],
    capabilityBadges: ["协作"],
    platformBadges: ["Web"],
    publishedAt: "2026-04-21T08:00:00.000Z",
    weeklyViews: 0,
    status: "published",
  },
  {
    id: "product-raycast",
    name: "Raycast",
    slug: "raycast",
    description: "桌面效率产品里的强风格样本，首页包装、品牌气质和功能呈现都很完整。",
    logo: "/placeholder-logo.svg",
    categoryId: "product-efficiency-collaboration",
    channelType: "vibe-products",
    websiteUrl: "https://www.raycast.com/",
    previewImageUrl: "/placeholder.jpg",
    fullDescription: toolDetailTemplate("Raycast", "一个适合参考桌面效率产品如何讲清价值的案例。", [
      "首页设计和品牌表达是一体的",
      "桌面产品的能力展示做得干净直接",
      "适合参考强风格效率产品的包装方式",
    ]),
    referenceBadges: ["首页设计", "品牌表达"],
    capabilityBadges: [],
    platformBadges: ["桌面端"],
    publishedAt: "2026-04-20T08:00:00.000Z",
    weeklyViews: 0,
    status: "published",
  },
  {
    id: "product-notion",
    name: "Notion",
    slug: "notion",
    description: "复杂内容与协作产品里的长期样本，首页表达和信息结构都很有参考价值。",
    logo: "/placeholder-logo.svg",
    categoryId: "product-efficiency-collaboration",
    channelType: "vibe-products",
    websiteUrl: "https://www.notion.com/",
    previewImageUrl: "/placeholder.jpg",
    fullDescription: toolDetailTemplate("Notion", "一个适合参考效率协作产品如何兼顾表达和结构的长期样本。", [
      "首页设计能承载复杂卖点但依然有秩序",
      "信息架构稳定，适合拆多模块产品如何组织能力",
      "协作产品的统一感和扩展性都很强",
    ]),
    referenceBadges: ["首页设计", "信息架构"],
    capabilityBadges: ["协作"],
    platformBadges: ["Web"],
    publishedAt: "2026-04-19T08:00:00.000Z",
    weeklyViews: 0,
    status: "published",
  },
  {
    id: "product-granola",
    name: "Granola",
    slug: "granola",
    description: "AI 会议笔记产品里的轻盈样本，首页、引导和品牌气质都很完整。",
    logo: "/placeholder-logo.svg",
    categoryId: "product-efficiency-collaboration",
    channelType: "vibe-products",
    websiteUrl: "https://www.granola.ai/",
    previewImageUrl: "/placeholder.jpg",
    fullDescription: toolDetailTemplate("Granola", "一个适合参考 AI Native 效率产品如何做亲和表达的案例。", [
      "首页设计轻盈，但卖点依然足够明确",
      "Onboarding 心智清楚，适合参考首次使用如何降低心理门槛",
      "品牌表达温和统一，适合拆 AI 工具的人味感",
    ]),
    referenceBadges: ["首页设计", "Onboarding", "品牌表达"],
    capabilityBadges: ["AI Native"],
    platformBadges: ["桌面端"],
    publishedAt: "2026-04-18T08:00:00.000Z",
    weeklyViews: 0,
    status: "published",
  },
  {
    id: "product-arc",
    name: "Arc",
    slug: "arc",
    description: "效率产品里的强个性样本，首页设计和品牌表达几乎是同一件事。",
    logo: "/placeholder-logo.svg",
    categoryId: "product-efficiency-collaboration",
    channelType: "vibe-products",
    websiteUrl: "https://arc.net/",
    previewImageUrl: "/placeholder.jpg",
    fullDescription: toolDetailTemplate("Arc", "一个适合参考效率产品如何做强品牌表达的案例。", [
      "首页设计有强烈态度，但信息仍然可读",
      "品牌表达非常鲜明，适合参考产品气质如何落地",
      "适合研究桌面效率产品如何避免同质化",
    ]),
    referenceBadges: ["首页设计", "品牌表达"],
    capabilityBadges: [],
    platformBadges: ["桌面端"],
    publishedAt: "2026-04-17T08:00:00.000Z",
    weeklyViews: 0,
    status: "published",
  },
] as const

export function getFallbackToolBySlug(slug: string) {
  return fallbackTools.find((tool) => tool.slug === slug) ?? null
}
