export type CuratedToolOverride = {
  name?: string
  description: string
  fullDescription?: string
  websiteUrl?: string
}

export const curatedCategorySortOrders: Record<string, string[]> = {
  "AI 编程智能体": [
    "cursor",
    "codex",
    "claude-code",
    "github-copilot",
    "windsurf",
    "zed",
    "devin",
    "cline",
    "openhands",
    "aider",
    "jetbrains-ai-assistant",
    "kiro",
    "tabnine",
    "trae",
    "void",
    "pear-ai",
    "roo-code",
    "amp",
    "goose",
    "sweep",
  ],
  "界面生成": [
    "framer",
    "webflow",
    "v0",
    "relume",
    "bolt",
    "wix-studio",
    "typedream",
    "durable",
    "webstudio",
    "unicorn-platform",
  ],
  "全栈应用构建": [
    "replit",
    "lovable",
    "bubble",
    "flutterflow",
    "softr",
    "glide",
    "retool",
    "dify",
    "appsmith",
    "tooljet",
  ],
  "数据后端": [
    "supabase",
    "firebase",
    "neon",
    "convex",
    "appwrite",
    "planetscale",
    "xata",
    "turso",
    "nhost",
    "pocketbase",
  ],
  "自动化流程": [
    "zapier",
    "n8n",
    "make",
    "pipedream",
    "workato",
    "tray-ai",
    "activepieces",
    "ifttt",
    "tines",
    "kestra",
  ],
  "部署发布": [
    "vercel",
    "cloudflare",
    "netlify",
    "railway",
    "render",
    "fly-io",
    "aws-amplify",
    "digitalocean-app-platform",
    "koyeb",
    "northflank",
  ],
  "设计与原型": [
    "figma",
    "miro",
    "figjam",
    "tldraw",
    "excalidraw",
    "whimsical",
    "lucidchart",
    "mural",
    "balsamiq",
    "protopie",
  ],
}

export type CuratedExtraTool = {
  id: string
  name: string
  slug: string
  description: string
  fullDescription: string
  logo: string
  categoryName: string
  channelType: "vibe-tools" | "vibe-products"
  websiteUrl: string
  previewImageUrl: string
  publishedAt: string
  weeklyViews: number
}

export const curatedToolOverrides: Record<string, CuratedToolOverride> = {
  framer: {
    description: "用 AI 和可视化编辑快速搭建并发布网站，内置 CMS、分析、SEO 和本地化能力。",
  },
  softr: {
    description: "基于数据快速搭建业务应用、客户门户和内部工具，无需写代码也能上线。",
  },
  cline: {
    description: "开源编码 agent，可在编辑器和命令行里理解代码库、改代码并自动化开发流程。",
  },
  neon: {
    description: "面向团队和 agents 的 Serverless Postgres，强调自动扩缩、分支和快速交付。",
  },
  vercel: {
    description: "面向前端和 AI 应用的云平台，负责构建、部署、预览和线上交付。",
  },
  figma: {
    description: "把头脑风暴、设计、原型和开发协作放到同一平台里的产品设计工具。",
  },
  cursor: {
    description: "理解代码库、支持自然语言编辑和 agent 工作流的 AI 代码编辑器。",
  },
  openhands: {
    description: "可真正执行工程任务的开源 coding agent 平台，不只是给代码建议。",
  },
  xata: {
    description: "基于 Postgres 的数据平台，主打分支能力和面向 Serverless 场景的开发体验。",
  },
  netlify: {
    description: "集 AI、Serverless 和全球交付于一体的 Web 开发与部署平台。",
  },
  miro: {
    description: "适合白板协作、流程梳理和团队共创的可视化工作空间。",
  },
  webflow: {
    description: "把可视化建站、CMS、分析与优化整合到一起的网站体验平台。",
  },
  devin: {
    description: "能规划、编写、运行和测试代码的 AI 软件工程师，适合处理复杂工程任务。",
  },
  n8n: {
    description: "通过可视化工作流连接 API、Webhook 和 AI 组件的自动化平台。",
  },
  cloudflare: {
    description: "提供全球部署、数据库、存储与 AI 能力的一体化开发者平台。",
  },
  whimsical: {
    description: "把流程图、线框图、思维导图和文档协作放到同一无限画布里的工具。",
  },
  relume: {
    description: "用 AI 生成站点地图、线框图和风格指南，并可导出到 Figma、Webflow 和 React。",
  },
  pipedream: {
    description: "连接 API、AI、数据库和 MCP 工具，适合快速搭建自动化与集成流程。",
  },
  railway: {
    description: "一体化云平台，适合用 Git 或容器快速部署应用、数据库和后台任务。",
  },
  tldraw: {
    description: "支持无限画布和 SDK 的白板工具，适合草图表达、流程梳理和原型协作。",
  },
  windsurf: {
    description: "以 agentic IDE 为核心，让 AI 和开发者在同一编辑器里协作编码。",
  },
  lovable: {
    description: "通过聊天生成并迭代全栈 Web 应用，让想法更快变成可运行产品。",
  },
  zed: {
    description: "强调速度、协作和 AI 工作流的高性能代码编辑器。",
  },
  aider: {
    description: "在终端里和 LLM 结对编程，适合基于现有代码库持续修改和迭代。",
  },
  render: {
    description: "面向 builders 的云平台，可统一部署应用、agents、数据库和后台任务。",
  },
  excalidraw: {
    description: "轻量手绘风在线白板，适合快速画草图、流程图和产品想法。",
  },
  replit: {
    description: "从自然语言直接生成、运行并部署应用的一体化在线开发平台。",
  },
  trae: {
    description: "定位为 AI Engineer 的开发环境，可独立理解、执行并交付软件任务。",
  },
  supabase: {
    description: "以 Postgres 为核心，提供 Auth、Storage、Edge Functions 等能力的后端平台。",
  },
  make: {
    description: "用可视化方式构建工作流和 AI agents 的自动化平台，强调可见性和控制力。",
  },
  v0: {
    description: "通过提示快速生成应用、网站和界面，并能直接发布到线上。",
  },
  bubble: {
    description: "结合 AI 提示和可视化编辑，无代码构建并发布 Web 与移动应用。",
  },
  "jetbrains-ai-assistant": {
    description: "集成在 JetBrains IDE 中的 AI 编码助手，支持聊天、补全、生成与重构。",
  },
  firebase: {
    description: "Google 的应用开发平台，覆盖构建、运行和增长现代 Web 与移动应用所需能力。",
  },
  zapier: {
    description: "把 AI、agents 和业务系统连接起来，并提供治理能力的自动化平台。",
  },
  bolt: {
    description: "在浏览器里通过提示生成、运行和迭代网站、Web 应用和移动应用。",
  },
  flutterflow: {
    description: "可视化构建高质量定制应用，并可导出 Flutter 代码加速上线。",
  },
  "claude-code": {
    description: "Anthropic 的 agentic 编码系统，可读代码库、跨文件改动、跑测试并交付结果。",
  },
  convex: {
    description: "让前端、后端和数据库实时同步的应用后端平台。",
  },
  activepieces: {
    description: "开源自动化平台，也支持构建能连接现有工具的 AI agents。",
  },
  linear: {
    description: "界面克制、节奏干净，是很多产品团队参考信息密度与秩序感的样本。",
  },
  raycast: {
    description: "桌面效率产品里视觉统一性很强，功能表达和品牌气质结合得很完整。",
  },
  notion: {
    description: "在复杂信息组织和简洁界面之间拿捏得很好，适合参考内容产品的视觉秩序。",
  },
  granola: {
    description: "AI 会议笔记产品里气质很完整，适合参考轻盈、友好的产品呈现方式。",
  },
  arc: {
    description: "界面表达和品牌气质高度统一，适合参考有明显个性的产品视觉组织方式。",
  },
  codex: {
    description: "OpenAI 的编码 agent，可并行处理真实工程任务，并贯通 CLI、IDE 与云端工作流。",
    fullDescription:
      "OpenAI 的 Codex 是面向真实软件工程工作的编码 agent，既能在 CLI 和 IDE 里协作，也支持多 agent 并行完成更长链路的开发任务。",
    websiteUrl: "https://openai.com/codex",
  },
}

export const curatedExtraTools: CuratedExtraTool[] = [
  {
    id: "tool-figjam",
    name: "FigJam",
    slug: "figjam",
    description: "在线协作白板，适合脑暴、流程梳理、会议同步和团队共创。",
    fullDescription: "FigJam 是 Figma 的在线协作白板产品，适合把脑暴、讨论、流程梳理和项目协作放到同一画布里完成。",
    logo: "/placeholder-logo.svg",
    categoryName: "设计与原型",
    channelType: "vibe-tools",
    websiteUrl: "https://www.figma.com/figjam/",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T09:29:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-mural",
    name: "Mural",
    slug: "mural",
    description: "视觉协作白板，适合远程 workshop、策略对齐和跨团队共创。",
    fullDescription: "Mural 是面向团队协作的视觉工作空间，适合在白板上完成头脑风暴、规划、对齐和创新讨论。",
    logo: "/placeholder-logo.svg",
    categoryName: "设计与原型",
    channelType: "vibe-tools",
    websiteUrl: "https://www.mural.co/",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T09:28:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-lucidchart",
    name: "Lucidchart",
    slug: "lucidchart",
    description: "智能图表工具，适合快速制作流程图、系统图和架构图。",
    fullDescription: "Lucidchart 是强调智能化和协作的图表工具，适合把流程、系统关系和复杂结构快速可视化。",
    logo: "/placeholder-logo.svg",
    categoryName: "设计与原型",
    channelType: "vibe-tools",
    websiteUrl: "https://www.lucidchart.com/pages",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T09:27:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-balsamiq",
    name: "Balsamiq",
    slug: "balsamiq",
    description: "低保真线框图工具，适合在写代码前快速画出页面和交互草稿。",
    fullDescription: "Balsamiq 是低保真线框图工具，适合在开发前快速表达界面布局、功能结构和交互想法。",
    logo: "/placeholder-logo.svg",
    categoryName: "设计与原型",
    channelType: "vibe-tools",
    websiteUrl: "https://balsamiq.com/",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T09:26:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-protopie",
    name: "ProtoPie",
    slug: "protopie",
    description: "高保真交互原型工具，适合验证复杂动效、多设备和真实交互体验。",
    fullDescription: "ProtoPie 是高保真交互原型工具，适合把复杂交互、传感器、跨设备和动态逻辑做成可体验的原型。",
    logo: "/placeholder-logo.svg",
    categoryName: "设计与原型",
    channelType: "vibe-tools",
    websiteUrl: "https://www.protopie.io/",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T09:25:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-typedream",
    name: "Typedream",
    slug: "typedream",
    description: "无代码网站生成工具，适合快速做落地页、个人站和数字产品页面。",
    fullDescription: "Typedream 是无代码网站构建工具，适合快速发布个人站、产品页、内容页和数字商品展示页。",
    logo: "/placeholder-logo.svg",
    categoryName: "界面生成",
    channelType: "vibe-tools",
    websiteUrl: "https://typedream.com/",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T09:24:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-webstudio",
    name: "Webstudio",
    slug: "webstudio",
    description: "开源网站构建器，适合用可视化方式做高性能、可导出的营销网站。",
    fullDescription: "Webstudio 是开源网站构建器，适合在可视化界面里构建高性能前端，并保留导出与自托管自由度。",
    logo: "/placeholder-logo.svg",
    categoryName: "界面生成",
    channelType: "vibe-tools",
    websiteUrl: "https://webstudio.is/",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T09:23:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-wix-studio",
    name: "Wix Studio",
    slug: "wix-studio",
    description: "面向专业团队的网站创建平台，适合多站点协作和可视化交付。",
    fullDescription: "Wix Studio 是面向机构、团队和专业创作者的网站创建平台，适合多项目协作、CMS 编辑和高效交付。",
    logo: "/placeholder-logo.svg",
    categoryName: "界面生成",
    channelType: "vibe-tools",
    websiteUrl: "https://www.wix.com/studio",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T09:22:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-durable",
    name: "Durable",
    slug: "durable",
    description: "AI 网站生成器，适合用极短时间搭出可上线的企业展示页。",
    fullDescription: "Durable 是 AI 网站生成器，适合在很短时间里生成一个可发布、可继续编辑的业务站点。",
    logo: "/placeholder-logo.svg",
    categoryName: "界面生成",
    channelType: "vibe-tools",
    websiteUrl: "https://durable.co/",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T09:21:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-unicorn-platform",
    name: "Unicorn Platform",
    slug: "unicorn-platform",
    description: "面向创业者的落地页搭建工具，适合快速发布 SaaS 与产品介绍页。",
    fullDescription: "Unicorn Platform 是面向创业者和小团队的页面构建工具，适合快速上线产品官网和 SaaS 落地页。",
    logo: "/placeholder-logo.svg",
    categoryName: "界面生成",
    channelType: "vibe-tools",
    websiteUrl: "https://unicornplatform.com/",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T09:20:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-glide",
    name: "Glide",
    slug: "glide",
    description: "把业务数据快速变成可用应用，适合运营后台、门户和移动工作台。",
    fullDescription: "Glide 适合把表格和业务数据快速转成可用应用，让团队更快搭出业务后台、客户端和内部工具。",
    logo: "/placeholder-logo.svg",
    categoryName: "全栈应用构建",
    channelType: "vibe-tools",
    websiteUrl: "https://www.glideapps.com/",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T09:19:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-retool",
    name: "Retool",
    slug: "retool",
    description: "面向开发者的应用搭建平台，适合内部工具、运营面板和数据工作流。",
    fullDescription: "Retool 适合把数据源、可视化编辑和代码能力放到同一环境里，快速搭出企业内部应用。",
    logo: "/placeholder-logo.svg",
    categoryName: "全栈应用构建",
    channelType: "vibe-tools",
    websiteUrl: "https://retool.com/apps",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T09:18:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-tooljet",
    name: "ToolJet",
    slug: "tooljet",
    description: "开源低代码应用平台，适合快速搭内部工具并连接数据库与 API。",
    fullDescription: "ToolJet 是开源低代码应用平台，适合快速构建能连接数据库、API 和业务系统的内部工具。",
    logo: "/placeholder-logo.svg",
    categoryName: "全栈应用构建",
    channelType: "vibe-tools",
    websiteUrl: "https://www.tooljet.ai/",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T09:17:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-appsmith",
    name: "Appsmith",
    slug: "appsmith",
    description: "开源低代码平台，适合在企业内快速构建可定制业务应用。",
    fullDescription: "Appsmith 是开源低代码应用平台，适合企业团队用拖拽和代码结合的方式快速交付业务工具。",
    logo: "/placeholder-logo.svg",
    categoryName: "全栈应用构建",
    channelType: "vibe-tools",
    websiteUrl: "https://www.appsmith.com/",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T09:16:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-dify",
    name: "Dify",
    slug: "dify",
    description: "生产级 AI 应用开发平台，适合把 agent、RAG 和工作流拼成完整产品。",
    fullDescription: "Dify 提供 agentic workflows、RAG、集成与可观测性，适合快速把 AI 能力做成真正可上线的产品。",
    logo: "/placeholder-logo.svg",
    categoryName: "全栈应用构建",
    channelType: "vibe-tools",
    websiteUrl: "https://dify.ai/",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T09:15:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-github-copilot",
    name: "GitHub Copilot",
    slug: "github-copilot",
    description: "覆盖编辑器、命令行和 GitHub 流程的 AI 编码助手。",
    fullDescription: "GitHub Copilot 把 AI 编码能力带到编辑器、终端和 GitHub 工作流里，适合持续协作式开发。",
    logo: "/placeholder-logo.svg",
    categoryName: "AI 编程智能体",
    channelType: "vibe-tools",
    websiteUrl: "https://github.com/features/copilot",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T09:14:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-tabnine",
    name: "Tabnine",
    slug: "tabnine",
    description: "强调企业上下文、治理和安全控制的 AI 编码平台。",
    fullDescription: "Tabnine 把企业上下文和治理能力带进 AI 编码工作流，适合对安全和控制要求更高的团队。",
    logo: "/placeholder-logo.svg",
    categoryName: "AI 编程智能体",
    channelType: "vibe-tools",
    websiteUrl: "https://www.tabnine.com/",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T09:13:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-kiro",
    name: "Kiro",
    slug: "kiro",
    description: "带 IDE 和 CLI 的 agentic AI 开发环境，强调从原型到生产的 spec-driven workflow。",
    fullDescription: "Kiro 提供 IDE 和 CLI 两个入口，强调通过 spec-driven 的方式把 AI 开发从原型推进到生产阶段。",
    logo: "/placeholder-logo.svg",
    categoryName: "AI 编程智能体",
    channelType: "vibe-tools",
    websiteUrl: "https://kiro.dev/",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T09:12:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-void",
    name: "Void",
    slug: "void",
    description: "开源 AI 代码编辑器，支持任意模型并强调数据控制权。",
    fullDescription: "Void 是开源 AI 代码编辑器，强调模型选择自由和数据控制权，适合希望更可控地使用 AI 编码的人。",
    logo: "/placeholder-logo.svg",
    categoryName: "AI 编程智能体",
    channelType: "vibe-tools",
    websiteUrl: "https://voideditor.com/",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T09:11:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-pear-ai",
    name: "PearAI",
    slug: "pear-ai",
    description: "面向下一个项目的 AI code editor，适合快速开始生成式编码工作流。",
    fullDescription: "PearAI 是面向生成式开发工作流的 AI code editor，适合快速开始一个新项目并持续迭代。",
    logo: "/placeholder-logo.svg",
    categoryName: "AI 编程智能体",
    channelType: "vibe-tools",
    websiteUrl: "https://www.trypear.ai/",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T09:10:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-codex",
    name: "Codex",
    slug: "codex",
    description: curatedToolOverrides.codex.description,
    fullDescription:
      curatedToolOverrides.codex.fullDescription ??
      curatedToolOverrides.codex.description,
    logo: "/placeholder-logo.svg",
    categoryName: "AI 编程智能体",
    channelType: "vibe-tools",
    websiteUrl: curatedToolOverrides.codex.websiteUrl ?? "https://openai.com/codex",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T09:30:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-amp",
    name: "Amp",
    slug: "amp",
    description: "前沿编码 agent，可在终端中调用主流模型处理真实开发任务。",
    fullDescription: "Amp 是面向前沿模型的编码 agent，适合在终端里处理真实工程任务并迭代结果。",
    logo: "/placeholder-logo.svg",
    categoryName: "AI 编程智能体",
    channelType: "vibe-tools",
    websiteUrl: "https://ampcode.com/",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T09:09:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-roo-code",
    name: "Roo Code",
    slug: "roo-code",
    description: "可在 VS Code 本地交互、也能在云端委派任务的 AI 开发团队。",
    fullDescription: "Roo Code 既支持本地交互式开发，也支持把任务委派给云端 agent，适合团队化的 AI 协作开发。",
    logo: "/placeholder-logo.svg",
    categoryName: "AI 编程智能体",
    channelType: "vibe-tools",
    websiteUrl: "https://roocode.com/",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T09:08:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-goose",
    name: "Goose",
    slug: "goose",
    description: "开源 on-machine AI agent，适合自动化代码迁移、项目理解和本地任务执行。",
    fullDescription: "Goose 是 Block 推出的开源 on-machine AI agent，适合在本地执行复杂任务、代码迁移和工程自动化。",
    logo: "/placeholder-logo.svg",
    categoryName: "AI 编程智能体",
    channelType: "vibe-tools",
    websiteUrl: "https://block.github.io/goose/",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T09:07:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-sweep",
    name: "Sweep",
    slug: "sweep",
    description: "面向 JetBrains 的 AI 编码助手，适合代码改动、审查和自动化辅助。",
    fullDescription: "Sweep 是 JetBrains 里的 AI 编码助手，适合在 IDE 内完成代码改动、评审和自动化辅助工作。",
    logo: "/placeholder-logo.svg",
    categoryName: "AI 编程智能体",
    channelType: "vibe-tools",
    websiteUrl: "https://sweep.dev/",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T09:06:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-appwrite",
    name: "Appwrite",
    slug: "appwrite",
    description: "开源一体化开发平台，包含认证、数据库、存储和函数等后端能力。",
    fullDescription: "Appwrite 是开源一体化开发平台，适合把认证、数据库、存储和函数能力一起作为后端底座使用。",
    logo: "/placeholder-logo.svg",
    categoryName: "数据后端",
    channelType: "vibe-tools",
    websiteUrl: "https://appwrite.io/",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T09:05:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-nhost",
    name: "Nhost",
    slug: "nhost",
    description: "基于 Postgres 的托管后端平台，集成 GraphQL、鉴权、存储和函数。",
    fullDescription: "Nhost 是基于 Postgres 的托管后端平台，适合需要 GraphQL、鉴权、存储和函数的一体化团队。",
    logo: "/placeholder-logo.svg",
    categoryName: "数据后端",
    channelType: "vibe-tools",
    websiteUrl: "https://nhost.io/",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T09:04:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-planetscale",
    name: "PlanetScale",
    slug: "planetscale",
    description: "全托管关系型数据库平台，强调性能、可靠性和分支式工作流。",
    fullDescription: "PlanetScale 是全托管关系型数据库平台，适合对性能、可靠性和数据库分支工作流有要求的团队。",
    logo: "/placeholder-logo.svg",
    categoryName: "数据后端",
    channelType: "vibe-tools",
    websiteUrl: "https://planetscale.com/",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T09:03:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-turso",
    name: "Turso",
    slug: "turso",
    description: "面向边缘场景的数据库平台，适合低延迟分布式应用。",
    fullDescription: "Turso 是面向边缘部署的数据库平台，适合需要低延迟、分布式和轻量化数据层的应用。",
    logo: "/placeholder-logo.svg",
    categoryName: "数据后端",
    channelType: "vibe-tools",
    websiteUrl: "https://turso.tech/",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T09:02:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-pocketbase",
    name: "PocketBase",
    slug: "pocketbase",
    description: "单文件开源后端，适合快速起步的小型 Web 应用和原型。",
    fullDescription: "PocketBase 是单文件开源后端，适合快速起步做原型、小型应用和轻量后端服务。",
    logo: "/placeholder-logo.svg",
    categoryName: "数据后端",
    channelType: "vibe-tools",
    websiteUrl: "https://pocketbase.io/",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T09:01:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-workato",
    name: "Workato",
    slug: "workato",
    description: "企业级集成与自动化平台，适合跨系统编排业务流程与 AI 动作。",
    fullDescription: "Workato 适合把企业里的系统集成、流程自动化和 AI 动作编排到统一工作流中。",
    logo: "/placeholder-logo.svg",
    categoryName: "自动化流程",
    channelType: "vibe-tools",
    websiteUrl: "https://www.workato.com/",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T09:00:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-tray-ai",
    name: "Tray.ai",
    slug: "tray-ai",
    description: "统一 agents、MCP、集成和自动化的企业编排平台。",
    fullDescription: "Tray.ai 适合把 agents、MCP、业务集成和自动化统一到一个企业级编排平台里。",
    logo: "/placeholder-logo.svg",
    categoryName: "自动化流程",
    channelType: "vibe-tools",
    websiteUrl: "https://tray.ai/",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T08:59:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-tines",
    name: "Tines",
    slug: "tines",
    description: "智能工作流平台，适合安全、IT 和跨团队自动化协作。",
    fullDescription: "Tines 是智能工作流平台，适合在安全、IT 和跨部门场景中快速构建自动化流程。",
    logo: "/placeholder-logo.svg",
    categoryName: "自动化流程",
    channelType: "vibe-tools",
    websiteUrl: "https://www.tines.com/",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T08:58:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-ifttt",
    name: "IFTTT",
    slug: "ifttt",
    description: "轻量无代码自动化平台，适合把常用应用和设备快速连起来。",
    fullDescription: "IFTTT 适合用无代码方式快速连接常见应用和设备，搭建轻量自动化流程。",
    logo: "/placeholder-logo.svg",
    categoryName: "自动化流程",
    channelType: "vibe-tools",
    websiteUrl: "https://ifttt.com/",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T08:57:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-kestra",
    name: "Kestra",
    slug: "kestra",
    description: "开源编排平台，适合数据、AI、基础设施与业务流程统一调度。",
    fullDescription: "Kestra 是开源编排平台，适合把数据、AI、基础设施和业务流程放到统一调度体系里管理。",
    logo: "/placeholder-logo.svg",
    categoryName: "自动化流程",
    channelType: "vibe-tools",
    websiteUrl: "https://kestra.io/",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T08:56:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-fly-io",
    name: "Fly.io",
    slug: "fly-io",
    description: "开发者导向的部署平台，适合把容器和应用分发到更靠近用户的位置。",
    fullDescription: "Fly.io 适合把应用和容器部署到更靠近用户的全球节点，并兼顾隔离性和部署灵活度。",
    logo: "/placeholder-logo.svg",
    categoryName: "部署发布",
    channelType: "vibe-tools",
    websiteUrl: "https://fly.io/",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T08:55:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-koyeb",
    name: "Koyeb",
    slug: "koyeb",
    description: "面向 API、推理和数据库的高性能无服务器基础设施平台。",
    fullDescription: "Koyeb 适合部署 API、AI 推理服务和数据库，强调高性能、全球分发和无服务器体验。",
    logo: "/placeholder-logo.svg",
    categoryName: "部署发布",
    channelType: "vibe-tools",
    websiteUrl: "https://www.koyeb.com/",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T08:54:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-northflank",
    name: "Northflank",
    slug: "northflank",
    description: "生产级 PaaS，适合从 Git 到生产环境快速部署服务、数据库和 jobs。",
    fullDescription: "Northflank 是生产级 PaaS，适合从 Git 仓库直接部署服务、数据库和 jobs，并一路扩展到生产环境。",
    logo: "/placeholder-logo.svg",
    categoryName: "部署发布",
    channelType: "vibe-tools",
    websiteUrl: "https://northflank.com/",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T08:53:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-aws-amplify",
    name: "AWS Amplify",
    slug: "aws-amplify",
    description: "AWS 的全栈应用平台，适合 Web 与移动前端的构建、托管和发布。",
    fullDescription: "AWS Amplify 适合在 AWS 体系里完成前端构建、托管、发布以及部分全栈能力整合。",
    logo: "/placeholder-logo.svg",
    categoryName: "部署发布",
    channelType: "vibe-tools",
    websiteUrl: "https://aws.amazon.com/amplify/",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T08:52:00.000Z",
    weeklyViews: 0,
  },
  {
    id: "tool-digitalocean-app-platform",
    name: "DigitalOcean App Platform",
    slug: "digitalocean-app-platform",
    description: "简化应用发布的 PaaS，适合用 Git 工作流快速部署 Web、API 和静态站。",
    fullDescription: "DigitalOcean App Platform 是简化发布流程的 PaaS，适合用 Git 直接部署 Web 应用、API 和静态站点。",
    logo: "/placeholder-logo.svg",
    categoryName: "部署发布",
    channelType: "vibe-tools",
    websiteUrl: "https://www.digitalocean.com/products/app-platform",
    previewImageUrl: "/placeholder.jpg",
    publishedAt: "2026-04-21T08:51:00.000Z",
    weeklyViews: 0,
  },
]
